site_name: Airy Dev Guide
site_description: 'Development guides for CogniPilot'
site_author: 'CogniPilot Foundation'
site_url: 'https://airy.cognipilot.org'

repo_name: 'CogniPilot/airy_docs'
repo_url: 'https://github.com/CogniPilot/airy_docs'

edit_uri: 'edit/main/docs/'

docs_dir: docs/

theme:
  language: en
  name: material
  custom_dir: theme_overrides
  logo: assets/CogniPilotLogoSite.png
  favicon: assets/CogniPilotLogoFavicon.png
  features:
    - content.code.copy
    - content.code.annotate

extra_css:
  - stylesheets/cognipilot-palette.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CogniPilot
    - icon: fontawesome/brands/discord
      link: https://discord.gg/cognipilot

copyright: Copyright &copy; 2023 CogniPilot Foundation. All Rights Reserved.

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - macros

nav:
    - Home: index.md
    - Getting Started: getting_started/install.md
    - Cerebri:
      - About: cerebri/about.md
      - Boards:
        - NXP® VMU RT1170: cerebri/boards/nxp_vmu_rt1170.md
        - NXP® MR CANHUBK3: cerebri/boards/nxp_mr_canhubk3.md
      - Platforms:
        - Rovers: cerebri/platforms/rovers.md
    - Cranium:
      - About: cranium/about.md
      - Corti: cranium/corti/corti.md
      - Synapse: cranium/synapse/synapse.md
      - Compute Hardware:
        - NXP® NavQPlus:
          - Setup: cranium/compute/navqplus/setup.md
    - Dream:
      - Worlds: dream/worlds/worlds.md
    - Electrode:
      - About: electrode/about.md
      - Joystick: electrode/joystick.md
      - RVIZ 2: electrode/rviz2.md
      - Foxglove: electrode/foxglove.md
    - Helmet:
      - About: helmet/about.md
    - Tools:
      - Cyecca: tools/cyecca/about.md
    - Reference Systems:
      - B3RB:
        - About: reference_systems/b3rb/about.md
        - Hardware Overview: reference_systems/b3rb/hardware.md
        - Setting up the System: reference_systems/b3rb/setup.md
        - Status Lighting and Sounds: reference_systems/b3rb/status.md
        - Using with Electrode: reference_systems/b3rb/electrode.md
        - Operating the platform: reference_systems/b3rb/operate.md
        - Running in Simulation: reference_systems/b3rb/simulation.md
    - Releases: "https://cognipilot.org/"
